FROM golang:1.25.4-alpine3.22 AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o data_inserter_service .

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/data_inserter_service .

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD pgrep viscosity_aggregator || exit 1

CMD [ "./data_inserter_service" ]